set(_CATKIN_CURRENT_PACKAGE "dynamic_reconfigure_example")
set(dynamic_reconfigure_example_VERSION "0.0.1")
set(dynamic_reconfigure_example_MAINTAINER "Lucas Walter <wsacul@gmail.com>")
set(dynamic_reconfigure_example_PACKAGE_FORMAT "1")
set(dynamic_reconfigure_example_BUILD_DEPENDS "dynamic_reconfigure" "nodelet" "roscpp" "std_msgs")
set(dynamic_reconfigure_example_BUILD_EXPORT_DEPENDS "dynamic_reconfigure" "nodelet" "roscpp" "std_msgs")
set(dynamic_reconfigure_example_BUILDTOOL_DEPENDS "catkin")
set(dynamic_reconfigure_example_BUILDTOOL_EXPORT_DEPENDS )
set(dynamic_reconfigure_example_EXEC_DEPENDS "dynamic_reconfigure" "nodelet" "roscpp" "std_msgs")
set(dynamic_reconfigure_example_RUN_DEPENDS "dynamic_reconfigure" "nodelet" "roscpp" "std_msgs")
set(dynamic_reconfigure_example_TEST_DEPENDS )
set(dynamic_reconfigure_example_DOC_DEPENDS )
set(dynamic_reconfigure_example_URL_WEBSITE "https://github.com/lucasw/dynamic_reconfigure_example")
set(dynamic_reconfigure_example_URL_BUGTRACKER "")
set(dynamic_reconfigure_example_URL_REPOSITORY "")
set(dynamic_reconfigure_example_DEPRECATED "")