//#line 2 "/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
// 
// File autogenerated for the dynamic_reconfigure_example package 
// by the dynamic_reconfigure package.
// Please do not edit.
// 
// ********************************************************/

#ifndef __dynamic_reconfigure_example__EXAMPLECONFIG_H__
#define __dynamic_reconfigure_example__EXAMPLECONFIG_H__

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace dynamic_reconfigure_example
{
  class ExampleConfigStatics;
  
  class ExampleConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l, 
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      
      virtual void clamp(ExampleConfig &config, const ExampleConfig &max, const ExampleConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const ExampleConfig &config1, const ExampleConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, ExampleConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const ExampleConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, ExampleConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const ExampleConfig &config) const = 0;
      virtual void getValue(const ExampleConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;
    
    template <class T>
    class ParamDescription : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level, 
          std::string a_description, std::string a_edit_method, T ExampleConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T (ExampleConfig::* field);

      virtual void clamp(ExampleConfig &config, const ExampleConfig &max, const ExampleConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;
        
        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const ExampleConfig &config1, const ExampleConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, ExampleConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const ExampleConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, ExampleConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const ExampleConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const ExampleConfig &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, ExampleConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    template<class T, class PT>
    class GroupDescription : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, ExampleConfig &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T (PT::* field);
      std::vector<ExampleConfig::AbstractGroupDescriptionConstPtr> groups;
    };
    
class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(ExampleConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("double_param"==(*_i)->name){double_param = boost::any_cast<double>(val);}
        if("int_param"==(*_i)->name){int_param = boost::any_cast<int>(val);}
        if("bool_param"==(*_i)->name){bool_param = boost::any_cast<bool>(val);}
        if("str_param"==(*_i)->name){str_param = boost::any_cast<std::string>(val);}
        if("extra_long_test_name_str"==(*_i)->name){extra_long_test_name_str = boost::any_cast<std::string>(val);}
        if("enum_param"==(*_i)->name){enum_param = boost::any_cast<int>(val);}
      }
    }

    double double_param;
int int_param;
bool bool_param;
std::string str_param;
std::string extra_long_test_name_str;
int enum_param;

    bool state;
    std::string name;

    class SUB
{
  public:
    SUB()
    {
      state = true;
      name = "Sub";
    }

    void setParams(ExampleConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("small_double"==(*_i)->name){small_double = boost::any_cast<double>(val);}
        if("big_double"==(*_i)->name){big_double = boost::any_cast<double>(val);}
      }
    }

    double small_double;
double big_double;

    bool state;
    std::string name;

    
}sub;

class SUB2
{
  public:
    SUB2()
    {
      state = true;
      name = "Sub2";
    }

    void setParams(ExampleConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("small_double2"==(*_i)->name){small_double2 = boost::any_cast<double>(val);}
      }
    }

    double small_double2;

    bool state;
    std::string name;

    
}sub2;

}groups;



//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double double_param;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int int_param;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool bool_param;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      std::string str_param;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      std::string extra_long_test_name_str;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int enum_param;
//#line 11 "/home/pi/catkin_ws_1/src/dynamic_reconfigure_tools/dynamic_reconfigure_example/cfg/Example.cfg"
      double small_double;
//#line 12 "/home/pi/catkin_ws_1/src/dynamic_reconfigure_tools/dynamic_reconfigure_example/cfg/Example.cfg"
      double big_double;
//#line 15 "/home/pi/catkin_ws_1/src/dynamic_reconfigure_tools/dynamic_reconfigure_example/cfg/Example.cfg"
      double small_double2;
//#line 218 "/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("ExampleConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }
    
    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }
    
    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const ExampleConfig &__max__ = __getMax__();
      const ExampleConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const ExampleConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }
    
    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const ExampleConfig &__getDefault__();
    static const ExampleConfig &__getMax__();
    static const ExampleConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();
    
  private:
    static const ExampleConfigStatics *__get_statics__();
  };
  
  template <> // Max and min are ignored for strings.
  inline void ExampleConfig::ParamDescription<std::string>::clamp(ExampleConfig &config, const ExampleConfig &max, const ExampleConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class ExampleConfigStatics
  {
    friend class ExampleConfig;
    
    ExampleConfigStatics()
    {
ExampleConfig::GroupDescription<ExampleConfig::DEFAULT, ExampleConfig> Default("Default", "", 0, 0, true, &ExampleConfig::groups);
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.double_param = 0.1;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.double_param = 50.0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.double_param = 20.0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ExampleConfig::AbstractParamDescriptionConstPtr(new ExampleConfig::ParamDescription<double>("double_param", "double", 1, "frame rate Hz", "", &ExampleConfig::double_param)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ExampleConfig::AbstractParamDescriptionConstPtr(new ExampleConfig::ParamDescription<double>("double_param", "double", 1, "frame rate Hz", "", &ExampleConfig::double_param)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.int_param = 1;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.int_param = 256;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.int_param = 50;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ExampleConfig::AbstractParamDescriptionConstPtr(new ExampleConfig::ParamDescription<int>("int_param", "int", 1, "integer", "", &ExampleConfig::int_param)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ExampleConfig::AbstractParamDescriptionConstPtr(new ExampleConfig::ParamDescription<int>("int_param", "int", 1, "integer", "", &ExampleConfig::int_param)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.bool_param = 0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.bool_param = 1;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.bool_param = 0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ExampleConfig::AbstractParamDescriptionConstPtr(new ExampleConfig::ParamDescription<bool>("bool_param", "bool", 1, "bool", "", &ExampleConfig::bool_param)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ExampleConfig::AbstractParamDescriptionConstPtr(new ExampleConfig::ParamDescription<bool>("bool_param", "bool", 1, "bool", "", &ExampleConfig::bool_param)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.str_param = "";
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.str_param = "";
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.str_param = "test";
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ExampleConfig::AbstractParamDescriptionConstPtr(new ExampleConfig::ParamDescription<std::string>("str_param", "str", 1, "string", "", &ExampleConfig::str_param)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ExampleConfig::AbstractParamDescriptionConstPtr(new ExampleConfig::ParamDescription<std::string>("str_param", "str", 1, "string", "", &ExampleConfig::str_param)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.extra_long_test_name_str = "";
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.extra_long_test_name_str = "";
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.extra_long_test_name_str = "test";
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ExampleConfig::AbstractParamDescriptionConstPtr(new ExampleConfig::ParamDescription<std::string>("extra_long_test_name_str", "str", 1, "string with long label", "", &ExampleConfig::extra_long_test_name_str)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ExampleConfig::AbstractParamDescriptionConstPtr(new ExampleConfig::ParamDescription<std::string>("extra_long_test_name_str", "str", 1, "string with long label", "", &ExampleConfig::extra_long_test_name_str)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.enum_param = 0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.enum_param = 3;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.enum_param = 1;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ExampleConfig::AbstractParamDescriptionConstPtr(new ExampleConfig::ParamDescription<int>("enum_param", "int", 0, "A size parameter which is edited via an enum", "{'enum_description': 'An enum to set size', 'enum': [{'srcline': 21, 'description': 'A small constant', 'srcfile': '/home/pi/catkin_ws_1/src/dynamic_reconfigure_tools/dynamic_reconfigure_example/cfg/Example.cfg', 'cconsttype': 'const int', 'value': 0, 'ctype': 'int', 'type': 'int', 'name': 'Small'}, {'srcline': 22, 'description': 'A medium constant', 'srcfile': '/home/pi/catkin_ws_1/src/dynamic_reconfigure_tools/dynamic_reconfigure_example/cfg/Example.cfg', 'cconsttype': 'const int', 'value': 1, 'ctype': 'int', 'type': 'int', 'name': 'Medium'}, {'srcline': 23, 'description': 'A large constant', 'srcfile': '/home/pi/catkin_ws_1/src/dynamic_reconfigure_tools/dynamic_reconfigure_example/cfg/Example.cfg', 'cconsttype': 'const int', 'value': 2, 'ctype': 'int', 'type': 'int', 'name': 'Large'}, {'srcline': 24, 'description': 'An extra large constant', 'srcfile': '/home/pi/catkin_ws_1/src/dynamic_reconfigure_tools/dynamic_reconfigure_example/cfg/Example.cfg', 'cconsttype': 'const int', 'value': 3, 'ctype': 'int', 'type': 'int', 'name': 'ExtraLarge'}]}", &ExampleConfig::enum_param)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ExampleConfig::AbstractParamDescriptionConstPtr(new ExampleConfig::ParamDescription<int>("enum_param", "int", 0, "A size parameter which is edited via an enum", "{'enum_description': 'An enum to set size', 'enum': [{'srcline': 21, 'description': 'A small constant', 'srcfile': '/home/pi/catkin_ws_1/src/dynamic_reconfigure_tools/dynamic_reconfigure_example/cfg/Example.cfg', 'cconsttype': 'const int', 'value': 0, 'ctype': 'int', 'type': 'int', 'name': 'Small'}, {'srcline': 22, 'description': 'A medium constant', 'srcfile': '/home/pi/catkin_ws_1/src/dynamic_reconfigure_tools/dynamic_reconfigure_example/cfg/Example.cfg', 'cconsttype': 'const int', 'value': 1, 'ctype': 'int', 'type': 'int', 'name': 'Medium'}, {'srcline': 23, 'description': 'A large constant', 'srcfile': '/home/pi/catkin_ws_1/src/dynamic_reconfigure_tools/dynamic_reconfigure_example/cfg/Example.cfg', 'cconsttype': 'const int', 'value': 2, 'ctype': 'int', 'type': 'int', 'name': 'Large'}, {'srcline': 24, 'description': 'An extra large constant', 'srcfile': '/home/pi/catkin_ws_1/src/dynamic_reconfigure_tools/dynamic_reconfigure_example/cfg/Example.cfg', 'cconsttype': 'const int', 'value': 3, 'ctype': 'int', 'type': 'int', 'name': 'ExtraLarge'}]}", &ExampleConfig::enum_param)));
ExampleConfig::GroupDescription<ExampleConfig::DEFAULT::SUB, ExampleConfig::DEFAULT> Sub("Sub", "", 0, 1, true, &ExampleConfig::DEFAULT::sub);
//#line 11 "/home/pi/catkin_ws_1/src/dynamic_reconfigure_tools/dynamic_reconfigure_example/cfg/Example.cfg"
      __min__.small_double = 0.0;
//#line 11 "/home/pi/catkin_ws_1/src/dynamic_reconfigure_tools/dynamic_reconfigure_example/cfg/Example.cfg"
      __max__.small_double = 0.5;
//#line 11 "/home/pi/catkin_ws_1/src/dynamic_reconfigure_tools/dynamic_reconfigure_example/cfg/Example.cfg"
      __default__.small_double = 0.001;
//#line 11 "/home/pi/catkin_ws_1/src/dynamic_reconfigure_tools/dynamic_reconfigure_example/cfg/Example.cfg"
      Sub.abstract_parameters.push_back(ExampleConfig::AbstractParamDescriptionConstPtr(new ExampleConfig::ParamDescription<double>("small_double", "double", 1, "small num test", "", &ExampleConfig::small_double)));
//#line 11 "/home/pi/catkin_ws_1/src/dynamic_reconfigure_tools/dynamic_reconfigure_example/cfg/Example.cfg"
      __param_descriptions__.push_back(ExampleConfig::AbstractParamDescriptionConstPtr(new ExampleConfig::ParamDescription<double>("small_double", "double", 1, "small num test", "", &ExampleConfig::small_double)));
//#line 12 "/home/pi/catkin_ws_1/src/dynamic_reconfigure_tools/dynamic_reconfigure_example/cfg/Example.cfg"
      __min__.big_double = 1000.0;
//#line 12 "/home/pi/catkin_ws_1/src/dynamic_reconfigure_tools/dynamic_reconfigure_example/cfg/Example.cfg"
      __max__.big_double = 1500000000.0;
//#line 12 "/home/pi/catkin_ws_1/src/dynamic_reconfigure_tools/dynamic_reconfigure_example/cfg/Example.cfg"
      __default__.big_double = 500000000.0;
//#line 12 "/home/pi/catkin_ws_1/src/dynamic_reconfigure_tools/dynamic_reconfigure_example/cfg/Example.cfg"
      Sub.abstract_parameters.push_back(ExampleConfig::AbstractParamDescriptionConstPtr(new ExampleConfig::ParamDescription<double>("big_double", "double", 1, "big num test", "", &ExampleConfig::big_double)));
//#line 12 "/home/pi/catkin_ws_1/src/dynamic_reconfigure_tools/dynamic_reconfigure_example/cfg/Example.cfg"
      __param_descriptions__.push_back(ExampleConfig::AbstractParamDescriptionConstPtr(new ExampleConfig::ParamDescription<double>("big_double", "double", 1, "big num test", "", &ExampleConfig::big_double)));
//#line 123 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Sub.convertParams();
//#line 123 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.groups.push_back(ExampleConfig::AbstractGroupDescriptionConstPtr(new ExampleConfig::GroupDescription<ExampleConfig::DEFAULT::SUB, ExampleConfig::DEFAULT>(Sub)));
//#line 123 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(ExampleConfig::AbstractGroupDescriptionConstPtr(new ExampleConfig::GroupDescription<ExampleConfig::DEFAULT::SUB, ExampleConfig::DEFAULT>(Sub)));
ExampleConfig::GroupDescription<ExampleConfig::DEFAULT::SUB2, ExampleConfig::DEFAULT> Sub2("Sub2", "", 0, 2, true, &ExampleConfig::DEFAULT::sub2);
//#line 15 "/home/pi/catkin_ws_1/src/dynamic_reconfigure_tools/dynamic_reconfigure_example/cfg/Example.cfg"
      __min__.small_double2 = 0.0;
//#line 15 "/home/pi/catkin_ws_1/src/dynamic_reconfigure_tools/dynamic_reconfigure_example/cfg/Example.cfg"
      __max__.small_double2 = 0.5;
//#line 15 "/home/pi/catkin_ws_1/src/dynamic_reconfigure_tools/dynamic_reconfigure_example/cfg/Example.cfg"
      __default__.small_double2 = 0.001;
//#line 15 "/home/pi/catkin_ws_1/src/dynamic_reconfigure_tools/dynamic_reconfigure_example/cfg/Example.cfg"
      Sub2.abstract_parameters.push_back(ExampleConfig::AbstractParamDescriptionConstPtr(new ExampleConfig::ParamDescription<double>("small_double2", "double", 1, "small num test", "", &ExampleConfig::small_double2)));
//#line 15 "/home/pi/catkin_ws_1/src/dynamic_reconfigure_tools/dynamic_reconfigure_example/cfg/Example.cfg"
      __param_descriptions__.push_back(ExampleConfig::AbstractParamDescriptionConstPtr(new ExampleConfig::ParamDescription<double>("small_double2", "double", 1, "small num test", "", &ExampleConfig::small_double2)));
//#line 123 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Sub2.convertParams();
//#line 123 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.groups.push_back(ExampleConfig::AbstractGroupDescriptionConstPtr(new ExampleConfig::GroupDescription<ExampleConfig::DEFAULT::SUB2, ExampleConfig::DEFAULT>(Sub2)));
//#line 123 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(ExampleConfig::AbstractGroupDescriptionConstPtr(new ExampleConfig::GroupDescription<ExampleConfig::DEFAULT::SUB2, ExampleConfig::DEFAULT>(Sub2)));
//#line 246 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 246 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(ExampleConfig::AbstractGroupDescriptionConstPtr(new ExampleConfig::GroupDescription<ExampleConfig::DEFAULT, ExampleConfig>(Default)));
//#line 356 "/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<ExampleConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__); 
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__); 
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__); 
    }
    std::vector<ExampleConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<ExampleConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    ExampleConfig __max__;
    ExampleConfig __min__;
    ExampleConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const ExampleConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static ExampleConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &ExampleConfig::__getDescriptionMessage__() 
  {
    return __get_statics__()->__description_message__;
  }

  inline const ExampleConfig &ExampleConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }
  
  inline const ExampleConfig &ExampleConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }
  
  inline const ExampleConfig &ExampleConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }
  
  inline const std::vector<ExampleConfig::AbstractParamDescriptionConstPtr> &ExampleConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<ExampleConfig::AbstractGroupDescriptionConstPtr> &ExampleConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const ExampleConfigStatics *ExampleConfig::__get_statics__()
  {
    const static ExampleConfigStatics *statics;
  
    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = ExampleConfigStatics::get_instance();
    
    return statics;
  }

//#line 21 "/home/pi/catkin_ws_1/src/dynamic_reconfigure_tools/dynamic_reconfigure_example/cfg/Example.cfg"
      const int Example_Small = 0;
//#line 22 "/home/pi/catkin_ws_1/src/dynamic_reconfigure_tools/dynamic_reconfigure_example/cfg/Example.cfg"
      const int Example_Medium = 1;
//#line 23 "/home/pi/catkin_ws_1/src/dynamic_reconfigure_tools/dynamic_reconfigure_example/cfg/Example.cfg"
      const int Example_Large = 2;
//#line 24 "/home/pi/catkin_ws_1/src/dynamic_reconfigure_tools/dynamic_reconfigure_example/cfg/Example.cfg"
      const int Example_ExtraLarge = 3;
}

#endif // __EXAMPLERECONFIGURATOR_H__
