set(_CATKIN_CURRENT_PACKAGE "dynamic_reconfigure_tools")
set(dynamic_reconfigure_tools_VERSION "0.0.1")
set(dynamic_reconfigure_tools_MAINTAINER "Lucas Walter <lucasw_backwards@gmail.com>")
set(dynamic_reconfigure_tools_PACKAGE_FORMAT "1")
set(dynamic_reconfigure_tools_BUILD_DEPENDS "dynamic_reconfigure" "roslint" "rospy" "rqt_gui_py")
set(dynamic_reconfigure_tools_BUILD_EXPORT_DEPENDS "dynamic_reconfigure" "rospy" "rqt_gui_py")
set(dynamic_reconfigure_tools_BUILDTOOL_DEPENDS "catkin")
set(dynamic_reconfigure_tools_BUILDTOOL_EXPORT_DEPENDS )
set(dynamic_reconfigure_tools_EXEC_DEPENDS "dynamic_reconfigure" "rospy" "rqt_gui_py")
set(dynamic_reconfigure_tools_RUN_DEPENDS "dynamic_reconfigure" "rospy" "rqt_gui_py")
set(dynamic_reconfigure_tools_TEST_DEPENDS )
set(dynamic_reconfigure_tools_DOC_DEPENDS )
set(dynamic_reconfigure_tools_URL_WEBSITE "")
set(dynamic_reconfigure_tools_URL_BUGTRACKER "")
set(dynamic_reconfigure_tools_URL_REPOSITORY "")
set(dynamic_reconfigure_tools_DEPRECATED "")