set(_CATKIN_CURRENT_PACKAGE "rqt_dr_single")
set(rqt_dr_single_VERSION "0.0.0")
set(rqt_dr_single_MAINTAINER "Lucas Walter <wsacul@gmail.com>")
set(rqt_dr_single_PACKAGE_FORMAT "1")
set(rqt_dr_single_BUILD_DEPENDS "dynamic_reconfigure" "roslint" "rospy" "rqt_gui_py")
set(rqt_dr_single_BUILD_EXPORT_DEPENDS "dynamic_reconfigure" "rospy" "rqt_gui_py")
set(rqt_dr_single_BUILDTOOL_DEPENDS "catkin")
set(rqt_dr_single_BUILDTOOL_EXPORT_DEPENDS )
set(rqt_dr_single_EXEC_DEPENDS "dynamic_reconfigure" "rospy" "rqt_gui_py")
set(rqt_dr_single_RUN_DEPENDS "dynamic_reconfigure" "rospy" "rqt_gui_py")
set(rqt_dr_single_TEST_DEPENDS )
set(rqt_dr_single_DOC_DEPENDS )
set(rqt_dr_single_URL_WEBSITE "")
set(rqt_dr_single_URL_BUGTRACKER "")
set(rqt_dr_single_URL_REPOSITORY "")
set(rqt_dr_single_DEPRECATED "")