set(rqt_dr_single_SETUP_PY_VERSION "0.0.0")
set(rqt_dr_single_SETUP_PY_SCRIPTS "")
set(rqt_dr_single_SETUP_PY_PACKAGES "rqt_dr_single")
set(rqt_dr_single_SETUP_PY_PACKAGE_DIRS "src/rqt_dr_single")
set(rqt_dr_single_SETUP_PY_MODULES "")
set(rqt_dr_single_SETUP_PY_MODULE_DIRS "")