# CMake generated Testfile for 
# Source directory: /home/pi/catkin_ws_1/src/ros_comm/utilities/xmlrpcpp/test
# Build directory: /home/pi/catkin_ws_1/build_isolated/xmlrpcpp/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_xmlrpcpp_gtest_xmlrpcvalue_base64 "/home/pi/catkin_ws_1/build_isolated/xmlrpcpp/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/pi/catkin_ws_1/build_isolated/xmlrpcpp/test_results/xmlrpcpp/gtest-xmlrpcvalue_base64.xml" "--return-code" "/home/pi/catkin_ws_1/devel_isolated/xmlrpcpp/lib/xmlrpcpp/xmlrpcvalue_base64 --gtest_output=xml:/home/pi/catkin_ws_1/build_isolated/xmlrpcpp/test_results/xmlrpcpp/gtest-xmlrpcvalue_base64.xml")
add_test(_ctest_xmlrpcpp_gtest_test_base64 "/home/pi/catkin_ws_1/build_isolated/xmlrpcpp/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/pi/catkin_ws_1/build_isolated/xmlrpcpp/test_results/xmlrpcpp/gtest-test_base64.xml" "--return-code" "/home/pi/catkin_ws_1/devel_isolated/xmlrpcpp/lib/xmlrpcpp/test_base64 --gtest_output=xml:/home/pi/catkin_ws_1/build_isolated/xmlrpcpp/test_results/xmlrpcpp/gtest-test_base64.xml")
add_test(_ctest_xmlrpcpp_gtest_HelloTest "/home/pi/catkin_ws_1/build_isolated/xmlrpcpp/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/pi/catkin_ws_1/build_isolated/xmlrpcpp/test_results/xmlrpcpp/gtest-HelloTest.xml" "--return-code" "/home/pi/catkin_ws_1/devel_isolated/xmlrpcpp/lib/xmlrpcpp/HelloTest --gtest_output=xml:/home/pi/catkin_ws_1/build_isolated/xmlrpcpp/test_results/xmlrpcpp/gtest-HelloTest.xml")
add_test(_ctest_xmlrpcpp_gtest_test_dispatch_live "/home/pi/catkin_ws_1/build_isolated/xmlrpcpp/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/pi/catkin_ws_1/build_isolated/xmlrpcpp/test_results/xmlrpcpp/gtest-test_dispatch_live.xml" "--return-code" "/home/pi/catkin_ws_1/devel_isolated/xmlrpcpp/lib/xmlrpcpp/test_dispatch_live --gtest_output=xml:/home/pi/catkin_ws_1/build_isolated/xmlrpcpp/test_results/xmlrpcpp/gtest-test_dispatch_live.xml")
add_test(_ctest_xmlrpcpp_gtest_test_ulimit "/home/pi/catkin_ws_1/build_isolated/xmlrpcpp/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/pi/catkin_ws_1/build_isolated/xmlrpcpp/test_results/xmlrpcpp/gtest-test_ulimit.xml" "--return-code" "/home/pi/catkin_ws_1/devel_isolated/xmlrpcpp/lib/xmlrpcpp/test_ulimit --gtest_output=xml:/home/pi/catkin_ws_1/build_isolated/xmlrpcpp/test_results/xmlrpcpp/gtest-test_ulimit.xml")
add_test(_ctest_xmlrpcpp_gtest_test_client "/home/pi/catkin_ws_1/build_isolated/xmlrpcpp/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/pi/catkin_ws_1/build_isolated/xmlrpcpp/test_results/xmlrpcpp/gtest-test_client.xml" "--return-code" "/home/pi/catkin_ws_1/devel_isolated/xmlrpcpp/lib/xmlrpcpp/test_client --gtest_output=xml:/home/pi/catkin_ws_1/build_isolated/xmlrpcpp/test_results/xmlrpcpp/gtest-test_client.xml")
add_test(_ctest_xmlrpcpp_gtest_test_dispatch "/home/pi/catkin_ws_1/build_isolated/xmlrpcpp/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/pi/catkin_ws_1/build_isolated/xmlrpcpp/test_results/xmlrpcpp/gtest-test_dispatch.xml" "--return-code" "/home/pi/catkin_ws_1/devel_isolated/xmlrpcpp/lib/xmlrpcpp/test_dispatch --gtest_output=xml:/home/pi/catkin_ws_1/build_isolated/xmlrpcpp/test_results/xmlrpcpp/gtest-test_dispatch.xml")
add_test(_ctest_xmlrpcpp_gtest_test_socket "/home/pi/catkin_ws_1/build_isolated/xmlrpcpp/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/pi/catkin_ws_1/build_isolated/xmlrpcpp/test_results/xmlrpcpp/gtest-test_socket.xml" "--return-code" "/home/pi/catkin_ws_1/devel_isolated/xmlrpcpp/lib/xmlrpcpp/test_socket --gtest_output=xml:/home/pi/catkin_ws_1/build_isolated/xmlrpcpp/test_results/xmlrpcpp/gtest-test_socket.xml")
add_test(_ctest_xmlrpcpp_gtest_TestValues "/home/pi/catkin_ws_1/build_isolated/xmlrpcpp/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/pi/catkin_ws_1/build_isolated/xmlrpcpp/test_results/xmlrpcpp/gtest-TestValues.xml" "--return-code" "/home/pi/catkin_ws_1/devel_isolated/xmlrpcpp/lib/xmlrpcpp/TestValues --gtest_output=xml:/home/pi/catkin_ws_1/build_isolated/xmlrpcpp/test_results/xmlrpcpp/gtest-TestValues.xml")
add_test(_ctest_xmlrpcpp_gtest_test_util "/home/pi/catkin_ws_1/build_isolated/xmlrpcpp/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/pi/catkin_ws_1/build_isolated/xmlrpcpp/test_results/xmlrpcpp/gtest-test_util.xml" "--return-code" "/home/pi/catkin_ws_1/devel_isolated/xmlrpcpp/lib/xmlrpcpp/test_util --gtest_output=xml:/home/pi/catkin_ws_1/build_isolated/xmlrpcpp/test_results/xmlrpcpp/gtest-test_util.xml")
add_test(_ctest_xmlrpcpp_gtest_TestXml "/home/pi/catkin_ws_1/build_isolated/xmlrpcpp/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/pi/catkin_ws_1/build_isolated/xmlrpcpp/test_results/xmlrpcpp/gtest-TestXml.xml" "--return-code" "/home/pi/catkin_ws_1/devel_isolated/xmlrpcpp/lib/xmlrpcpp/TestXml --gtest_output=xml:/home/pi/catkin_ws_1/build_isolated/xmlrpcpp/test_results/xmlrpcpp/gtest-TestXml.xml")
