set(rosparam_SETUP_PY_VERSION "1.15.11")
set(rosparam_SETUP_PY_SCRIPTS "scripts/rosparam")
set(rosparam_SETUP_PY_PACKAGES "rosparam")
set(rosparam_SETUP_PY_PACKAGE_DIRS "src/rosparam")
set(rosparam_SETUP_PY_MODULES "")
set(rosparam_SETUP_PY_MODULE_DIRS "")